const languageMap = {
    en: "English",
    fr: "French",
    es: "Spanish",
    de: "German",
    tr: "Turkish",
    ja: "Japanese",
    zh: "Chinese",
    ko: "Korean",
    hi: "Hindi",
    it: "Italian",
    ru: "Russian",
    pt: "Portuguese",
    ar: "Arabic",
    mn: "Mongolian",
    th: "Thai",
    id: "Indonesian",
    pl: "Polish",
    nl: "Dutch",
    no: "Norwegian",
    da: "Danish",
    fi: "Finnish",
    sv: "Swedish",
    cs: "Czech",
    hu: "Hungarian",
    ro: "Romanian",
    vi: "Vietnamese",
    bg: "Bulgarian",
    el: "Greek",
    sk: "Slovak",
    he: "Hebrew",
    sl: "Slovenian",
    hr: "Croatian",
    sr: "Serbian",
    et: "Estonian",
    lt: "Lithuanian",
  };

  export default languageMap;